"""create views table

Revision ID: 06f8d59308bb
Revises:
Create Date: 2026-09-18 23:38:02.633156

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "06f8d59308bb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
