"""Add Strategy Table

Revision ID: 4b818390b95a
Revises: a0b7b6dbb363
Create Date: 2026-09-19 01:46:15.471003

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4b818390b95a"
down_revision: str | Sequence[str] | None = "a0b7b6dbb363"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
