/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BacktestingIndexRouteImport } from './routes/backtesting/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments/index'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as MonitoringIndexRouteImport } from './routes/monitoring/index'
import { Route as RiskIndexRouteImport } from './routes/risk/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as StrategiesIndexRouteImport } from './routes/strategies/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestingIndexRoute = BacktestingIndexRouteImport.update({
  id: '/backtesting/',
  path: '/backtesting/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/data/',
  path: '/data/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/deployments/',
  path: '/deployments/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringIndexRoute = MonitoringIndexRouteImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskIndexRoute = RiskIndexRouteImport.update({
  id: '/risk/',
  path: '/risk/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiesIndexRoute = StrategiesIndexRouteImport.update({
  id: '/strategies/',
  path: '/strategies/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backtesting/': typeof BacktestingIndexRoute
  '/data/': typeof DataIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backtesting': typeof BacktestingIndexRoute
  '/data': typeof DataIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/monitoring': typeof MonitoringIndexRoute
  '/risk': typeof RiskIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/strategies': typeof StrategiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backtesting/': typeof BacktestingIndexRoute
  '/data/': typeof DataIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/monitoring/': typeof MonitoringIndexRoute
  '/risk/': typeof RiskIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/strategies/': typeof StrategiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backtesting/'
    | '/data/'
    | '/deployments/'
    | '/logs/'
    | '/monitoring/'
    | '/risk/'
    | '/settings/'
    | '/strategies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backtesting'
    | '/data'
    | '/deployments'
    | '/logs'
    | '/monitoring'
    | '/risk'
    | '/settings'
    | '/strategies'
  id:
    | '__root__'
    | '/'
    | '/backtesting/'
    | '/data/'
    | '/deployments/'
    | '/logs/'
    | '/monitoring/'
    | '/risk/'
    | '/settings/'
    | '/strategies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BacktestingIndexRoute: typeof BacktestingIndexRoute
  DataIndexRoute: typeof DataIndexRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MonitoringIndexRoute: typeof MonitoringIndexRoute
  RiskIndexRoute: typeof RiskIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StrategiesIndexRoute: typeof StrategiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtesting/': {
      id: '/backtesting/'
      path: '/backtesting'
      fullPath: '/backtesting/'
      preLoaderRoute: typeof BacktestingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/': {
      id: '/data/'
      path: '/data'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/deployments'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring/': {
      id: '/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof MonitoringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk/': {
      id: '/risk/'
      path: '/risk'
      fullPath: '/risk/'
      preLoaderRoute: typeof RiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategies/': {
      id: '/strategies/'
      path: '/strategies'
      fullPath: '/strategies/'
      preLoaderRoute: typeof StrategiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BacktestingIndexRoute: BacktestingIndexRoute,
  DataIndexRoute: DataIndexRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MonitoringIndexRoute: MonitoringIndexRoute,
  RiskIndexRoute: RiskIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StrategiesIndexRoute: StrategiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
